# -*- coding: utf-8 -*-
"""CODTECH TASK-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBrhfBqXKk4MfTOhRYN6ygK3F5CTZa4s
"""

import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

df = pd.read_csv('/content/drive/MyDrive/task-1/Student_performance_data _.csv')
df.head(10)

print("Dataset shape:", df.shape)
print("\nDataset info:")
df.info()

numeric_features = df.select_dtypes(include=['int64', 'float64']).columns
categorical_features = df.select_dtypes(include=['object']).columns

print("Numerical columns:", numeric_features)
print("Categorical columns:", categorical_features)

numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_pipeline, numeric_features),
    ('cat', categorical_pipeline, categorical_features)
])

processed_data = preprocessor.fit_transform(df)

print("Data pipeline executed successfully!")
print("Processed data shape:", processed_data.shape)

np.save('processed_data.npy', processed_data)

print("Processed data saved as processed_data.npy")

files.download('processed_data.npy')